name: Build 1.16.5

on:
  push:
    branches:
      - "1.16.5"
  pull_request:
    branches:
      - "1.16.5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Prepare ForgeGradle cache directories
        run: mkdir -p ~/.gradle/caches/forge_gradle/minecraft_user_repo/de/oceanlabs/mcp/mcp_config/1.16.5-20210115.111550

      - name: Build
        run: ./gradlew build --no-daemon
